name: Deploy Streamlit to Snowflake

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

            - name: Set up Python

              uses: actions/setup-python@v5

              with:

                python-version: '3.9'

      

            - name: Install Snowflake CLI

              run: |

                pip install --upgrade pip

                pip install snowflake-cli

      

            - name: Create Snowflake CLI Config

              shell: bash

              env:

                SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}

                SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}

                SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}

          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}

              run: |

                mkdir -p ~/.snowflake

                cat <<EOF > ~/.snowflake/config.toml

                [connections]

                [connections.default]

                accountname = "$SNOWFLAKE_ACCOUNT"

                username = "$SNOWFLAKE_USER"

                password = "$SNOWFLAKE_PASSWORD"

                warehouse = "$SNOWFLAKE_WAREHOUSE"

                EOF

                chmod 0600 ~/.snowflake/config.toml

      - name: Deploy Streamlit App
        env:
          SNOWSQL_CONFIG_PATH: ~/.snowflake/config.toml
        run: |
          snow streamlit deploy
