name: Deploy Streamlit to Snowflake

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Snowflake CLI
        uses: snowflakedb/snowflake-cli-action@v2.0
        with:
          account: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          user: ${{ secrets.SNOWFLAKE_USER }}
          password: ${{ secrets.SNOWFLAKE_PASSWORD }}
          warehouse: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          database: SUPERSUITE_DB
          schema: SUPERSUITE_SCHEMA

      - name: Deploy Streamlit App
        run: |
          snow streamlit deploy
